spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/spring-boot/study
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true # System.out? ?????? ?? SQL? ?? (??X)
        format_sql: true
        use_sql_comments: true # ???? JPQL ???? ? ? ??

logging.level:
  # logger? ?? ?????? ?? SQL? ?? (??)
  org.hibernate.SQL: debug
  # ?? ???? ?? ???
#  org.hibernate.type: trace